Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BubiSanat.Data;
using BubiSanat.Models;

namespace BubiSanat.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Categories.Include(c => c.TopCategory);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(short? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .Include(c => c.TopCategory)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            ViewData["TopCategoryId"] = new SelectList(_context.TopCategories, "Id", "Name");
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Info,TopCategoryId")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["TopCategoryId"] = new SelectList(_context.TopCategories, "Id", "Name", category.TopCategoryId);
            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(short? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            ViewData["TopCategoryId"] = new SelectList(_context.TopCategories, "Id", "Name", category.TopCategoryId);
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(short id, [Bind("Id,Name,Info,TopCategoryId")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TopCategoryId"] = new SelectList(_context.TopCategories, "Id", "Name", category.TopCategoryId);
            return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(short? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .Include(c => c.TopCategory)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(short id)
        {
            if (_context.Categories == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Categories'  is null.");
            }
            var category = await _context.Categories.FindAsync(id);
            if (category != null)
            {
                _context.Categories.Remove(category);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(short id)
        {
          return _context.Categories.Any(e => e.Id == id);
        }
    }
}

Controllers/HomeController.cs
using BubiSanat.Data;
using BubiSanat.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace BubiSanat.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        ApplicationDbContext _context;


        public HomeController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public async Task<IActionResult> Index(short? id = null)
        {
            IQueryable<Post> applicationDbContext = _context.Posts.Include(p => p.Category).Include(p => p.Author).Include(p => p.NextPost).Include(p => p.PreviousPost).OrderByDescending(p => p.CreatedAt);
            if (id != null)
            {
                applicationDbContext = applicationDbContext.Where(p => p.CategoryId == id.Value);
            }
            return View( applicationDbContext.ToList());
        }

        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult About()
        {
            return View();
        }
        public IActionResult Help()
        {
            return View();
        }
        public IActionResult UserAgreement()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BubiSanat.Data;
using BubiSanat.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace BubiSanat.Controllers
{
    public class PostsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PostsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Posts
        public async Task<IActionResult> Index(short? id = null)
        {
            IQueryable<Post> applicationDbContext = _context.Posts.Include(p => p.Category).Include(p => p.NextPost).Include(p => p.PreviousPost);
            if (id != null)
            {
                applicationDbContext = applicationDbContext.Where(p => p.CategoryId == id.Value);
            }
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Posts/Details/5
        
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null || _context.Posts == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .Include(p => p.Category)
                .Include(p => p.NextPost)
                .Include(p => p.PreviousPost)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }
            post.DisplayCount = post.DisplayCount + 1;
            _context.Update(post);
            _context.SaveChanges();
            return View(post);
        }
        public long Likes(long? id)
        {
            Post post =  _context.Posts.Where(p=>p.Id==id).FirstOrDefault();
           
            post.Likes = post.Likes + 1;
            _context.Update(post);
            _context.SaveChanges();
            return post.Likes;
        }

        [Authorize]
        // GET: Posts/Create
        public IActionResult Create()
        {
            string authorId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            List<Post> posts = _context.Posts.Where(p => p.AuthorId == User.FindFirstValue(ClaimTypes.NameIdentifier)).OrderBy(p => p.CreatedAt).ToList();

            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
            ViewData["NextPostId"] = new SelectList(_context.Posts, "Id", "Title");
            ViewData["PreviousPostId"] = new SelectList(_context.Posts, "Id", "Title");
            ViewData["authorId"] = authorId;
            return View();
        }

        [Authorize]
        // POST: Posts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,CategoryId,Content,PreviousPostId,NextPostId,Tags,AuthorId,FormImage")] Post post)
        {
            MemoryStream memoryStream;

            post.CreatedAt = DateTime.Now;
            if (ModelState.IsValid)
            {
                if(post.FormImage != null)
                {
                    memoryStream = new MemoryStream();
                    post.FormImage.CopyTo(memoryStream);
                    post.Image= memoryStream.ToArray();
                }
                _context.Add(post);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", post.CategoryId);
            ViewData["NextPostId"] = new SelectList(_context.Posts, "Id", "Content", post.NextPostId);
            ViewData["PreviousPostId"] = new SelectList(_context.Posts, "Id", "Content", post.PreviousPostId);
            return View(post);
        }

        // GET: Posts/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null || _context.Posts == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.FindAsync(id);
            if (post == null)
            {
                return NotFound();
            }
            if(post.AuthorId != User.FindFirstValue(ClaimTypes.NameIdentifier))
            {
                return Unauthorized();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", post.CategoryId);
            ViewData["NextPostId"] = new SelectList(_context.Posts, "Id", "Content", post.NextPostId);
            ViewData["PreviousPostId"] = new SelectList(_context.Posts, "Id", "Content", post.PreviousPostId);
            return View(post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Title,CreatedAt,CategoryId,Content,Deleted,PreviousPostId,NextPostId,Likes,DisplayCount,Tags")] Post post)
        {
            if (id != post.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(post);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostExists(post.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            if (post.AuthorId != User.FindFirstValue(ClaimTypes.NameIdentifier))
            {
                return Unauthorized();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", post.CategoryId);
            ViewData["NextPostId"] = new SelectList(_context.Posts, "Id", "Content", post.NextPostId);
            ViewData["PreviousPostId"] = new SelectList(_context.Posts, "Id", "Content", post.PreviousPostId);
            return View(post);
        }

        // GET: Posts/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null || _context.Posts == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .Include(p => p.Category)
                .Include(p => p.NextPost)
                .Include(p => p.PreviousPost)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }
            if (post.AuthorId != User.FindFirstValue(ClaimTypes.NameIdentifier))
            {
                return Unauthorized();
            }
            return View(post);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            if (_context.Posts == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Posts'  is null.");
            }
            var post = await _context.Posts.FindAsync(id);
            if (post != null)
            {
                _context.Posts.Remove(post);
            }
            if (post.AuthorId != User.FindFirstValue(ClaimTypes.NameIdentifier))
            {
                return Unauthorized();
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PostExists(long id)
        {
          return _context.Posts.Any(e => e.Id == id);
        }
    }
}

Controllers/UsersController.cs
using BubiSanat.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BubiSanat.Controllers
{
    public class UsersController : Controller
    {
        
        SignInManager<ApplicationUser> _signInManager;

        public UsersController(SignInManager<ApplicationUser> signInManager)
        {
            _signInManager = signInManager;
        }
        public IActionResult Index()
        {
            return View(_signInManager.UserManager.Users);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,UserName,Password,Email,ConfirmPassWord,Agreed")] ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
				if (applicationUser.Agreed == true)
				{
                    IdentityResult ıdentityResult = _signInManager.UserManager.CreateAsync(applicationUser, applicationUser.Password).Result;
                    return Redirect("~/");
                }
            }

            return View(applicationUser);

        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(string userName, string password)
        {
            Microsoft.AspNetCore.Identity.SignInResult identityResult;

            if (ModelState.IsValid)
            {
                identityResult = _signInManager.PasswordSignInAsync(userName, password, false, false).Result;

                if (identityResult.Succeeded == true)
                {
                    return Redirect("~/");
                }

            }

            return View();

        }

    }

}

Views/Home/About.cshtml
@using BubiSanat.Data
@using Microsoft.EntityFrameworkCore;
@inject ApplicationDbContext context;
@{
    List<TopCategory> topCategories = context.TopCategories.Include(t=>t.Categories).ToList();
    List<Category> categories = context.Categories.Where(c => c.TopCategoryId == null).ToList();
}
@{
	Layout=null;
}
<!DOCTYPE html>
<html lang="en" >
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BubiSanat</title>
    <link rel="stylesheet" href="~/font-awesome/css/all.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BubiSanat.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 ">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img height="35px"; src="https://bubisanat.s3.eu-central-1.amazonaws.com/bubisanat_logo.png"/>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <main class="header-offset">
      <div class="aboutus container d-flex flex-column justify-content-center align-items-center py-3">
  <h1 class="header">BuBi’ Sanat nedir? </h1>

  <h3 class="font-weight-bold">BuBi’ Sanat, düşünen ve üreten herkes için bir soluklanma alanıdır.</h3>
  <span class="paragraph">İmkanı olanın değil yeteneği olanın sivrileceği, işleyiş refleksinin -koşullar elverdiğince- nitelik önceliği üzerine kurulduğu bağımsız bir fikir-sanat platformudur.</span>

  <h1 class="header">YAYIN POLİTİKASI</h1>
  <h2 class="paragraph">Öncelikle BuBi' Sanat için emek ve zaman harcayan tüm bireylerin (editör, yazılımcı vb.) yaptığı işi tamamiyle gönüllü olarak yaptığını bilmenizi ve geri dönüşlerinizi koşulları da işin içine dahil ederek belirlemenizi rica ederiz. Biz bir firma ya da kurum değiliz. Kişisel yaşamından zaman artırarak bu işi sürdürmeye çalışan bir avuç sıradan insanız. Bilginize...</h2>

  <ol>
    <li>Onay süreci nasıl işler?</li>
    <ul>
      <li>Sitemize gönderilen tüm içerikler editöryal sürece tâbidir.</li>
      <li>Göndermiş olduğunuz tüm içerikler, editörlerimiz tarafından kronolojik sıraya göre değerlendirilir ve ortalama değerlendirme süresi üç (3) gündür.</li>
      <li>İçerikler TDK kurallarına göre gerekli görüldüğü durumlarda revize edilir ve yayına uygun hale getirilir.</li>
      <li>İçeriğinizde kasıtlı olarak yazım yanlışı içeren bir kelime/biçim oyunu vb. yaptıysanız "bunu kasıtlı olarak yaptığınızı" içeriğin bir kısmında belirtmeniz gerekmektedir.  Aksi durumdaki tüm içerikler yayın politikamıza ve TDK kurallarına uygun revize edilir.</li>
    </ul>
    <li>BuBi Sanat'ta nasıl içerikler yayınlanır?</li>
    <ul>
      <li>Yayın politikamıza paralel, ortalama ve üstü nitelikte bulunan tüm içerikler yayınlanır.</li>
      <li>Üretimler ele alınırken kullanıcının yalnız "şimdisiyle" değil tahmin edilen "beş yıl sonrası" ile de değerlendirilir.</li>
      <li>Platformumuzda yedi yaşından altmış beş yaşına kadar her bilinçten ve yaştan üretici mevcuttur.</li>
      <li>Burası sunum alanı olduğu kadar bir gelişim alanıdır. Ve gelişim bilinci her şeyin önünde tutulur.</li>
      <li>Seyir, iyi olanı daha iyiye, ortalama olanı iyiye yönlendirme şiarıyla ilerlemektedir. </li>
      <li>BuBi' Sanat bir karar mercii ya da bilirkişi komitesi değildir. BuBi' Sanat, aklıyla sanatın içinde var olmak isteyenlere; üretimlerini başka insanların algı ve yorumlarıyla buluşturmaları için naçizane bir alan inşa etme bilincindedir.</li>
      <li>Bu hususta siz kullanıcılarımızın içeriklere yapacağı eleştiri ve yorumlar oldukça önemlidir.</li>
      <li>BuBi' Sanat, her türlü ırkçı, cinsiyetçi, türcü, aşağılayıcı, hedef gösterici söylemin karşısındadır ve olmaya devam edecektir.</li>
    </ul>
    <li>YAZILMA MECBURİYETİ DAYATILMIŞ BİR KÜÇÜK MANİFESTO</li>
    <ul>
      <li>BuBi Sanat, yayınladığı her içeriğin "sanat" olduğunu iddia etmez. Bu karanlık ve sıkışık dünyada insanları bir nebze de olsa sanat konuşmaya ve sanatı cümle içinde sık sık kullanmaya teşvik eder. Yaptığı ve yapabileceği en iyi işin bu olacağına kanaat getirmiştir.</li>
      <li>BuBi' Sanat editörleri yalnızca kendi kişisel beğenilerine göre içerikler yayınlayacak olsaydı, haftada en fazla yirmi içerik yayınlayabilirdi. Yaşadığımız evreni, dünyayı, coğrayfayı ve koşulları göz önünde bulundurmadan üç adımda bir Rilke, Mallarme ya da Edip Cansever beklentisi nafile bir dilektir. </li>
      <li>BuBi' Sanat bir dergi veya yayınevi değildir. (Olmayacağının garantisi yoktur.)</li>
      <li>BuBi' Sanat, sizlere mütemadiyen kusursuz ve mükemmel içerikler vadetmez. Masum çabaları, dayanışmayı, sanatın her disiplinini önemseyen bir yaklaşımı ve samimiyeti vadeder.</li>
      <li>BuBi' Sanat, yola çıktığı andan itibaren yürüyüşünün yalnızlığını ve ne yaparsa yapsın eleştiriden/saldırıdan kurtulamayacağını anlamış insanlardan oluşan bir ekibin algısındadır ve sanatı kurtarmak gibi devasa bir söylemin altına imzasını atmamaktadır.</li>
      <li>BuBi' Sanat, on kişiye bile yeteneğini, aklını sunma imkanı tanısak; üç tertemiz bilinci düşünsel anlamda kendi mümkün-iyisine sevk edebilsek bize yeter, ilkesiyle yola devam etmektedir.</li>
      <li>BuBi' Sanat, hiç gereği yokken, yapmasa hiçbir şey kaybetmeyecekken gününün en az on saatini buraya harcayan ve sonucunda hakarete varan eleştirilerle, düşmancıl tavırlarla boğuşan insanlar tarafından yönetilmektedir.</li>
      <li>BuBi' Sanat sekizinci ayından itibaren salt yıkıcı ve kırıcı eleştirileri(!) muhatap almamaktadır.</li>
      <li>Eleştirilecek çok şey olduğunun farkında olduğumuzu bilmenizi ve iyileştirmeleri "düşün(e)mediğimizden değil, koşullar el vermediğinden" yapamadığımızı bilmenizi isteriz.</li>
      <li>Tüm içeriklerden kusursuzluk talebiniz varsa ve kusursuz bir yazar/şair/ressam vb. olduğunuzu düşünüyorsanız muhtemelen doğru yerde değilsiniz ve yanlış düşünüyorsunuz. :)</li>
    </ul>
  </ol>

  <span class="paragraph text-left w-100">Sevgilerle...</span>
  <br>
  <span class="paragraph text-left w-100">İletişim: <b>info@bubisanat.com</b></span>
  <span class="paragraph text-left w-100">Tanıtım/Reklam: <b>tanitim@bubisanat.com</b></span>

  <h3 class="paragraph text-left w-100">Platformumuzun sürdürülebilirliği için bizlere destek olmak isterseniz: <a href="https://kreosus.com/bubisanat" target="_blank" rel="noopener noreferrer">kreosus.com/bubisanat</a> </h3>
  
  <span class="paragraph text-left w-100">BuBi' Sanat Ekibi</span>
</div>

    </main>
</body>

Views/Home/Help.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h2>YARDIM</h2>

Views/Home/Index.cshtml
@model IEnumerable<BubiSanat.Models.Post>

@{
    ViewData["Title"] = "BubiSanat";
    string timeSpan;
    string content;

}
<script>
    	function Like(postid) {
			$.get("@Url.Action("Likes","Posts")?id=" + postid, function (likep) {
				$("#Likecount-"+postid).html(likep);
			});
	}
</script>

@foreach (var item in Model)
{
    if (item.Content.Length < 300)
    {
        content = item.Content;
    }
    else
    {
        content = item.Content.Substring(0, 300) + "...";
    }
    TimeSpan span = (DateTime.Now - item.CreatedAt);
    if (span.Days < 1)
    {
        timeSpan = span.Hours.ToString()+" saat";
    }
    else
    {
        timeSpan = span.Days.ToString()+" gün";
    }
    <div class="cardd card-nav-tabs">
        <a asp-controller="Posts" asp-action="Details" asp-route-id="@item.Id" class="carda"></a>
        <div class="Post">
    <ul>
        <li>
                <h2>@Html.DisplayFor(modelItem => item.Title)</h2>
                <div>
                    <p>@timeSpan Önce</p>
                </div>
        </li>
        <li>
            <strong>Yazar:</strong>
            <a asp-controller="Users" asp-action="Details" asp-route-id="@item.Id">@item.Author.UserName</a>
            <strong>Kategrori:
            <a asp-controller="Categories" asp-action="Details" asp-route-id="@item.Category.Id">@Html.DisplayFor(modelItem => item.Category.Name)</a>
            </strong>
        </li>
    </ul>
</div>  
<div class="Post-body">
    <div class="tab-content">
        <p>@content</p>
    </div>
    <div class="tab-content">
                @if (item.Image != null)
                {
                 <img src="data:image/jpeg;base64, @Convert.ToBase64String(@item.Image)"/>    
                }
    </div>
</div>
<div class="Post-footer">
    <div class="Post-footer-action" >
            <i id="Clicklike" class="fa fa-heart" onclick="Like('@item.Id.ToString()')"></i>
        <span id="Likecount-@item.Id.ToString()">@item.Likes</span>
    </div>
        <div class="Post-footer-action">
<i class="fa fa-comment"></i>
<span>1</span>
    </div>
        <div class="Post-footer-action">
        <i class="fa fa-eye"></i>
        <span>@item.DisplayCount.ToString()</span>
    </div>
</div>
    </div>
}

Views/Home/UserAgreement.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h2>Kullanı Sözleşmesi</h2>